name: 自动部署
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: main

      - name: 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "22.13.0"

      - name: 安装 Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g
      - name: 缓存 Hexo
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: 安装依赖
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm install --global gulp-cli
          npm update hexo --save
          npm install --save
          
      - name: 生成轻量朋友圈需要的json文件
        run: |
          npm install yamljs --save
          node link.js
          node friend.js

      - name: 生成追番页面文件
        run: |
          hexo bangumi -u

      - name: 生成静态文件
        run: |
          hexo clean
          hexo generate
          ls -l /home/runner/work/hexoSEVER/hexoSEVER/public/css/
          gulp
          ls -l /home/runner/work/hexoSEVER/hexoSEVER/
          node inline-css.js

      - name: 推送到Github仓库
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.HEXO_TOKEN }}
          repository-name: 661111/hexo-site-page
          branch: main
          folder: public
          commit-message: "${{ github.event.head_commit.message }} Updated By Github Actions"

      - name: 推送到服务器仓库
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器生成的私钥，例如 -----BEGIN RSA PRIVATE KEY-----xxxx-----END RSA PRIVATE KEY-----
          ARGS: "-avz --delete" # rsync参数
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }} # 服务器ip地址，例如 1.2.3.4
          REMOTE_USER: root # 登录用户，例如 ubuntu 注意应拥有该文件夹的权限，可以在root下为用户赋权 chown -R ubuntu:755 /www/wwwroot/hexo
          TARGET: /www/wwwroot/www.sxiaohe.top    # 服务器目录，例如 /www/wwwroot/hexo
          EXCLUDE: ".git/,.user.ini"            # 排除源路径中.git/ 目标路径中.user.ini 这俩不做同步操作